# Generated by Django 5.0.6 on 2024-05-23 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_reservations', '0002_country_alter_hotel_city_alter_hotel_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='city',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_reservations.country', verbose_name='Страна'),
        ),
    ]
